/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    FooterCustom: typeof import('./src/components/FooterCustom/index.vue')['default']
    FooterCustomOctocat: typeof import('./src/components/FooterCustom/octocat.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld/index.vue')['default']
    IconFont: typeof import('./src/components/IconFont/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutArea: typeof import('./src/components/Layout/LayoutArea.vue')['default']
    LayoutSection: typeof import('./src/components/Layout/LayoutSection.vue')['default']
    LayoutView: typeof import('./src/components/Layout/LayoutView.vue')['default']
    NavigationAvatar: typeof import('./src/components/Navigation/Avatar.vue')['default']
    NavigationChangeTheme: typeof import('./src/components/Navigation/ChangeTheme.vue')['default']
    NavigationNavBar: typeof import('./src/components/Navigation/NavBar.vue')['default']
    NavigationRefresh: typeof import('./src/components/Navigation/Refresh.vue')['default']
    NavigationSideAction: typeof import('./src/components/Navigation/Side/SideAction.vue')['default']
    NavigationSideGoBack: typeof import('./src/components/Navigation/Side/SideGoBack.vue')['default']
    NavigationSideLogo: typeof import('./src/components/Navigation/Side/SideLogo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
